# Generated by Django 4.2.7 on 2023-11-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedownload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва книги')),
                ('author', models.CharField(max_length=50, verbose_name='Автори')),
                ('source', models.CharField(default='Адмін', max_length=50, verbose_name='Завантажив')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
